server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///jt?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cc: debug