# 在注册中心中注册的服务id（服务名称）
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 175.27.231.28
    username: leesau
    password: a139131b
    port: 5672
  zipkin:
    sender:
      type: rabbit #如不配置的情况下默认是web，http直接连接  

#  8001,  8101,  8201
server:
  port: 8001

# defaultZone 表示默认地点
# 如果使用云服务，服务商可以提供不同地点的eureka服务器
# 如果没有云服务，就只能写 defaultZone
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
