# yml, yaml 耶冒
spring:
  application:
    name: user-service
  cloud:
    config:
      # 让配置中心的配置，不覆盖项目的本地配置和命令参数
      override-none: true
  rabbitmq:
    host: 175.27.231.28
    username: leesau
    password: a139131b
    port: 5672
  zipkin:
    sender:
      type: rabbit #如不配置的情况下默认是web，http直接连接

# 8001, 8101, 8201
server:
  port: 8101

# 自定义配置属性
# 配置测试用的用户数据 [{id:7, username:aa, password:aa}, {8..}, {9..}]
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},
             {\"id\":8, \"username\":\"def\",\"password\":\"456\"},
             {\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},
             {\"id\":99, \"username\":\"SSS\",\"password\":\"010\"}]"


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
